{{- if and .Values.enabled .Values.controlPlane.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway-stack.controlPlaneServiceAccountName" . }}
  labels:
    {{- include "gateway-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  {{- with .Values.controlPlane.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.controlPlane.serviceAccount.automount }}
{{- end }}
