{{- if and .Values.enabled .Values.guardianUI.enabled .Values.guardianUI.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway-stack.guardianUIServiceAccountName" . }}
  labels:
    {{- include "gateway-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: guardian-ui
  {{- with .Values.guardianUI.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.guardianUI.serviceAccount.automount }}
{{- end }}
