apiVersion: v1
kind: Secret
metadata:
  name: {{ include "governance-service.fullname" . }}
  labels:
    {{- include "governance-service.labels" . | nindent 4 }}
type: Opaque
data:

  DB_USER: {{ .Values.externalDatabase.user | b64enc }}
  DB_SSLMODE: {{ .Values.externalDatabase.sslmode | b64enc }}

  {{- if .Values.huggingFaceToken }}
  # Direct value provided
  HUGGING_FACE_TOKEN: {{ .Values.huggingFaceToken | b64enc }}
  {{- end }}

  {{- if .Values.credentialEncryptionKey }}
  # Direct value provided
  CREDENTIAL_ENCRYPTION_KEY: {{ .Values.credentialEncryptionKey | b64enc }}
  {{- end }}
