apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "governance-worker.fullname" . }}
  labels:
    {{- include "governance-worker.labels" . | nindent 4 }}
data:
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  WORKER_VERSION: "{{ .Values.config.scheduler.version }}"
  WORKER_TYPE: "{{ .Values.config.scheduler.workerType }}"
  WORKER_MAX_CONCURRENT_JOBS: "{{ .Values.config.scheduler.maxConcurrentJobs }}"
  WORKER_POLL_INTERVAL: "{{ .Values.config.scheduler.pollInterval }}"
  WORKER_HEARTBEAT_INTERVAL: "{{ .Values.config.scheduler.heartbeatInterval }}"
  WORKER_JOB_CLAIM_TTL: "{{ .Values.config.scheduler.jobClaimTTL }}"
  WORKER_CAPABILITIES: "{{ .Values.config.scheduler.capabilities }}"
  API_BASE_URL: "http://{{ include "governance-service.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}"
