"""YAML utilities for govctl."""

from typing import Any

import yaml

from govctl.core.models import PlatformConfig


class _LiteralStr(str):
    """String subclass that signals literal block style in YAML."""


def _literal_representer(dumper: yaml.Dumper, data: str) -> yaml.ScalarNode:
    """Represent multiline strings using literal block style (|)."""
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")


yaml.add_representer(_LiteralStr, _literal_representer)


def dump_yaml(data: dict[str, Any], width: int = 120) -> str:
    """Dump data to YAML string."""
    return yaml.dump(
        data,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=width,
    )


def dump_yaml_with_header(
    data: dict[str, Any],
    file_type: str,
    config: PlatformConfig,
) -> str:
    """Dump YAML with a descriptive header."""
    header = f"""# =============================================================================
# Governance Studio Platform - {file_type.upper()} FILE
# =============================================================================
# Generated by govctl for:
#   Cloud Provider: {config.cloud_provider.value.upper()}
#   Auth Provider:  {config.auth_provider.value}
#   Environment:    {config.environment}
#   Domain:         {config.domain}
# =============================================================================
#
"""

    if file_type == "secrets":
        header += """# IMPORTANT: Fill in all empty values before deploying!
#
# Generate random secrets with:
#   openssl rand -base64 32
#
# NOTE: For the database password, use hex encoding to avoid special
# characters (+, /, =) that break PostgreSQL connection URI parsing:
#   openssl rand -hex 32
#
# =============================================================================

"""

    return header + dump_yaml(data)
