# Example customer values.yaml for deploying Governance Studio
# Customize it for your specific environment

# Config values reused across various services/charts
_config: &config
  domain: &domain "govtest.dev.eqtylab.io"
  auth0Domain: &auth0Domain "governance-studio.us.auth0.com"
  auth0StagingDomain: &auth0StagingDomain "governance-studio-stag.us.auth0.com"

global:
  environmentType: "development" # Options: development, staging, production
  domain: *domain
  imagePullSecrets:
    - name: "ghcr-pull-secret"

  ingress:
    annotations:
      cert-manager.io/issuer: letsencrypt
    host: *domain

# --- Component: Governance Service API ---
governance-service:
  api:
    image:
      tag: "sha-94d85e4"
  worker:
    image:
      tag: "sha-94d85e4"

  ingress:
    hosts:
      - host: *domain
        paths:
          - path: "/governanceService(/|$)(.*)"
            pathType: "ImplementationSpecific"

    tls:
      - secretName: platform-tls
        hosts:
          - *domain

  config:
    appEnv: "development"

# --- Component: Gov Studio UI ---
governance-studio:
  image:
    tag: sha-03c2eb2-prod
  config:
    swaggerEnabled: "true"
    # API Configuration
    integrityServiceUrl: !join ["https://", *domain, "/integrityService"]
    apiUrl: !join ["https://", *domain]
    auth0Domain: *auth0Domain
    auth0ClientId: "oJlvzdhdlMDIs1PX1xeTM2B98TwZCtyw"
    auth0Audience: !join ["https://", *auth0Domain, "/api/v2/"]

    # Application Settings
    appHostname: *domain

  ingress:
    annotations:
      cert-manager.io/issuer: "letsencrypt"
    hosts:
      - host: *domain
        paths:
          - path: /
            pathType: Prefix

# --- Component: Integrity Service ---
integrity-service:
  ingress:
    hosts:
      - host: *domain
        paths:
          - path: "/integrityService(/|$)(.*)"
            pathType: "ImplementationSpecific"

    tls:
      - secretName: platform-tls
        hosts:
          - *domain

  image:
    tag: "b175486"

  env:
    integrityAppBlobStoreAccount: "umbrellachartstorage"
    integrityAppBlobStoreContainer: "root-blob-container"
    rustEnv: "development"
    rustBacktrace: "1"
    integrityServiceUrl: !join ["https://", *domain, "/integrityService"]

# --- Component: Auth Service ---
auth-service:
  image:
    tag: "sha-7bf195c"

  config:
    logging:
      level: debug
    idp:
      issuer: !join ["https://", *auth0StagingDomain, "/"]

      auth0:
        domain: *auth0StagingDomain
        managementAudience: !join ["https://", *auth0StagingDomain, "/api/v2/"]
        enableManagementAPI: true
        apiIdentifier: !join ["https://", *auth0StagingDomain, "/api/v2/"]
