"""Values.yaml generator."""

from typing import Any

from govctl.core.models import AuthProvider, PlatformConfig
from govctl.utils.yaml import dump_yaml_with_header, dump_yaml_sections
from govctl.generators.sections.auth_service import generate_auth_service_section
from govctl.generators.sections.governance_service import (
    generate_governance_service_section,
)
from govctl.generators.sections.governance_studio import (
    generate_governance_studio_section,
)
from govctl.generators.sections.integrity_service import (
    generate_integrity_service_section,
)
from govctl.generators.sections.postgresql import generate_postgresql_section
from govctl.generators.sections.keycloak import generate_keycloak_section
from govctl.generators.sections.entra import generate_entra_section


def generate_values(config: PlatformConfig) -> str:
    """Generate values.yaml content based on configuration."""
    header = f"""# =============================================================================
# Governance Studio Platform - VALUES FILE
# =============================================================================
# Generated by govctl for:
#   Cloud Provider: {config.cloud_provider.value.upper()}
#   Auth Provider:  {config.auth_provider.value}
#   Environment:    {config.environment}
#   Domain:         {config.domain}
# =============================================================================
#
"""

    sections: list[tuple[str, str, str, dict[str, Any]]] = [
        (
            "global",
            "Global Configuration",
            "Shared configuration values used across all services.",
            _generate_global_section(config),
        ),
        (
            "auth-service",
            "Auth Service",
            "Override values for the auth-service Helm chart.",
            generate_auth_service_section(config),
        ),
        (
            "governance-service",
            "Governance Service",
            "Override values for the governance-service Helm chart.",
            generate_governance_service_section(config),
        ),
        (
            "governance-studio",
            "Governance Studio",
            "Override values for the governance-studio Helm chart.",
            generate_governance_studio_section(config),
        ),
        (
            "integrity-service",
            "Integrity Service",
            "Override values for the integrity-service Helm chart.",
            generate_integrity_service_section(config),
        ),
        (
            "postgresql",
            "PostgreSQL",
            "Override values for the postgresql Helm chart.",
            generate_postgresql_section(config),
        ),
    ]

    if config.auth_provider == AuthProvider.KEYCLOAK:
        sections.append(
            (
                "keycloak",
                "Keycloak",
                "Override values for the keycloak Helm chart.",
                generate_keycloak_section(config),
            )
        )
    elif config.auth_provider == AuthProvider.ENTRA:
        sections.append(
            (
                "entra",
                "Entra",
                "Override values for the entra Helm chart.",
                generate_entra_section(config),
            )
        )

    return header + dump_yaml_sections(sections)


def _generate_global_section(config: PlatformConfig) -> dict[str, Any]:
    """Generate the global section of values.yaml."""
    return {
        "environmentType": config.environment,
        "domain": config.domain,
    }
