{{- if not .Values.config.idp.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-idp
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.config.idp.clientId | b64enc | quote }}
  client-secret: {{ .Values.config.idp.clientSecret | b64enc | quote }}
  {{- if eq .Values.config.idp.provider "auth0" }}
  {{- if .Values.config.idp.auth0.managementClientId }}
  mgmt-client-id: {{ .Values.config.idp.auth0.managementClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.idp.auth0.managementClientSecret }}
  mgmt-client-secret: {{ .Values.config.idp.auth0.managementClientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.config.idp.provider "keycloak" }}
  {{- if .Values.config.idp.keycloak.adminUsername }}
  admin-username: {{ .Values.config.idp.keycloak.adminUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.idp.keycloak.adminPassword }}
  admin-password: {{ .Values.config.idp.keycloak.adminPassword | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}

{{- if and (not .Values.postgresql.enabled) (not .Values.config.database.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-database
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.config.database.password | b64enc | quote }}
{{- end }}

{{- if eq .Values.config.keyVault.provider "azure" }}
{{- if not .Values.config.keyVault.azure.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-keyvault
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.config.keyVault.azure.clientId | b64enc | quote }}
  client-secret: {{ .Values.config.keyVault.azure.clientSecret | b64enc | quote }}
{{- end }}
{{- else if eq .Values.config.keyVault.provider "hashicorp" }}
{{- if not .Values.config.keyVault.hashicorp.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-keyvault
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.config.keyVault.hashicorp.token | b64enc | quote }}
{{- end }}
{{- end }}