#!/usr/bin/env bash
set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do SOURCE="$(readlink "$SOURCE")"; done
ROOTDIR="$(cd -P "$(dirname "$SOURCE")/../.." && pwd)"

# shellcheck source=../helpers/output.sh
source "$ROOTDIR/scripts/helpers/output.sh"
# shellcheck source=../helpers/assert.sh
source "$ROOTDIR/scripts/helpers/assert.sh"

# Function to display usage
usage() {
  echo -e "\
Bootstrap Keycloak realm, clients, scopes, and users for the Governance Platform

Usage: $0 -f <values-file> [options]
  -c, --chart-dir <dir>           Chart directory (default: $CHART_DIR)
  -f, --values <file>             Helm values file for keycloak-bootstrap chart (required)
  -h, --help                      Show this help message
  -n, --namespace <namespace>     Kubernetes namespace (required)
  -r, --release <name>            Helm release name (default: $BOOTSTRAP_RELEASE)

Examples:
  $0 -f $CHART_DIR/examples/values.yaml -n governance
  $0 -f my-values.yaml --namespace governance-stag
"
}

# Verify Keycloak is running and required secrets exist
check_prerequisites() {
  print_warn "Checking prerequisites..."

  # Check if Keycloak pod is running
  local keycloak_ready
  keycloak_ready=$(kubectl get pod -l app=keycloak -n "$NAMESPACE" -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null)
  if [ "$keycloak_ready" != "True" ]; then
    print_error "Keycloak pod is not ready"
    kubectl get pod -l app=keycloak -n "$NAMESPACE"
    exit 1
  fi
  print_info "Keycloak is running"

  # Check required secrets
  # Only keycloak-admin and platform-admin are mounted by the bootstrap job
  # Backend/worker client secrets are auto-generated by Keycloak
  local missing_secrets=()
  for secret in keycloak-admin platform-admin; do
    if ! kubectl get secret "$secret" -n "$NAMESPACE" &>/dev/null; then
      missing_secrets+=("$secret")
    fi
  done

  if [ ${#missing_secrets[@]} -gt 0 ]; then
    print_error "Missing required secrets:"
    printf '%s\n' "${missing_secrets[@]}"
    echo ""
    echo "Create them with:"
    echo "  kubectl create secret generic keycloak-admin --from-literal=password=<admin-password> -n $NAMESPACE"
    echo "  kubectl create secret generic platform-admin --from-literal=password=<platform-admin-password> -n $NAMESPACE"
    exit 1
  fi
  print_info "All required secrets exist"
}

# Deploy the keycloak-bootstrap Helm chart and monitor the job to completion
run_bootstrap() {
  # Clean up any existing bootstrap jobs
  print_warn "Cleaning up any existing bootstrap jobs..."
  kubectl delete job -l app.kubernetes.io/instance="$BOOTSTRAP_RELEASE" -n "$NAMESPACE" --ignore-not-found

  # Run the bootstrap
  print_warn "Running Keycloak bootstrap..."

  helm upgrade --install "$BOOTSTRAP_RELEASE" "$CHART_DIR" \
    -n "$NAMESPACE" \
    -f "$VALUES_FILE" \
    --wait \
    --timeout 10m

  # Get the job name
  local job_name
  job_name=$(kubectl get job -l app.kubernetes.io/instance="$BOOTSTRAP_RELEASE" -n "$NAMESPACE" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

  if [ -z "$job_name" ]; then
    print_error "Bootstrap job not found"
    exit 1
  fi

  echo "Bootstrap job: $job_name"

  # Monitor job completion
  print_warn "Monitoring bootstrap job..."

  local timeout=300
  local elapsed=0
  while [ $elapsed -lt $timeout ]; do
    local job_status
    local job_failed
    job_status=$(kubectl get job "$job_name" -n "$NAMESPACE" -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' 2>/dev/null)
    job_failed=$(kubectl get job "$job_name" -n "$NAMESPACE" -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}' 2>/dev/null)

    if [ "$job_status" = "True" ]; then
      print_info "Bootstrap completed successfully"
      break
    elif [ "$job_failed" = "True" ]; then
      print_error "Bootstrap job failed"
      echo "Job logs:"
      kubectl logs job/"$job_name" -n "$NAMESPACE" --tail=50
      exit 1
    fi

    echo -n "."
    sleep 5
    elapsed=$((elapsed + 5))
  done

  if [ $elapsed -ge $timeout ]; then
    print_error "Bootstrap job timed out"
    kubectl logs job/"$job_name" -n "$NAMESPACE" --tail=50
    exit 1
  fi

  # Show logs
  echo ""
  print_warn "Bootstrap logs (last 20 lines):"
  kubectl logs job/"$job_name" -n "$NAMESPACE" --tail=20

  # Cleanup completed job
  echo ""
  print_warn "Cleaning up completed job..."
  kubectl delete job "$job_name" -n "$NAMESPACE" --ignore-not-found
}

# Display credentials, OAuth clients, and Keycloak URLs
show_summary() {
  echo ""
  print_info "Bootstrap Complete!"
  echo ""
  echo "Keycloak URLs:"
  echo "- Admin Console: https://DOMAIN/keycloak/admin"
  echo "- Governance Realm: https://DOMAIN/keycloak/admin/governance/console"
  echo ""

  # Show credentials
  if kubectl get secret keycloak-admin -n "$NAMESPACE" &>/dev/null; then
    local admin_password
    admin_password=$(kubectl get secret --namespace "$NAMESPACE" keycloak-admin -o jsonpath="{.data.password}" | base64 -d)
    echo "Keycloak Admin (master realm):"
    echo "  Username: admin"
    echo "  Password: $admin_password"
    echo ""
  fi

  if kubectl get secret platform-admin -n "$NAMESPACE" &>/dev/null; then
    local platform_admin_password
    platform_admin_password=$(kubectl get secret --namespace "$NAMESPACE" platform-admin -o jsonpath="{.data.password}" | base64 -d)
    echo "Platform Admin (governance realm):"
    echo "  Username: platform-admin"
    echo "  Password: $platform_admin_password"
    echo ""
  fi

  echo "OAuth Clients:"
  echo "- Frontend: governance-platform-frontend (public client)"
  echo "- Backend: governance-platform-backend (confidential with service account)"
  echo "- Worker: governance-worker (service account only)"
  echo ""
  echo "Backend service account roles: query-users, view-users (realm-management)"

  echo ""
  print_info "Bootstrap process completed!"
}

# Configurable parameters
NAMESPACE=""
VALUES_FILE=""
CHART_DIR="$ROOTDIR/charts/keycloak-bootstrap"
BOOTSTRAP_RELEASE="keycloak-bootstrap"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
  -c | --chart-dir)
    CHART_DIR="$2"
    shift 2
    ;;
  -f | --values)
    VALUES_FILE="$2"
    shift 2
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  -n | --namespace)
    NAMESPACE="$2"
    shift 2
    ;;
  -r | --release)
    BOOTSTRAP_RELEASE="$2"
    shift 2
    ;;
  *)
    print_error "Unknown option: $1"
    usage
    exit 1
    ;;
  esac
done

# Validate prerequisites
assert_is_installed "helm"
assert_is_installed "kubectl"

# Validate required arguments
assert_not_empty "namespace" "$NAMESPACE" "Use -n or --namespace to provide a namespace."
assert_not_empty "values-file" "$VALUES_FILE" "Use -f or --values to provide a Helm values file."

# Validate path to file exists
assert_path_exists "chart-dir" "$CHART_DIR"

if [ ! -f "$VALUES_FILE" ]; then
  print_error "Values file not found: $VALUES_FILE"
  exit 1
fi

echo -e "\
Namespace:    $NAMESPACE
Release:      $BOOTSTRAP_RELEASE
Chart:        $CHART_DIR
Values:       $VALUES_FILE

This will create:
- Governance realm
- Platform admin user
- Three OAuth clients:
  - Frontend (public client)
  - Backend (confidential with service account)
  - Worker (service account only)
- Custom authorization scopes
- Service account roles for backend client
"

# Verify Keycloak
check_prerequisites
# Deploy the keycloak-bootstrap
run_bootstrap
# Display outputs
show_summary
