# Enablement Check
{{- if and .Values.global.secrets.create (eq .Values.global.secrets.keyManagement.provider "aws_kms") }}

# Data Validation
{{- if not .Values.global.secrets.keyManagement.aws_kms.secretName }}
  {{- fail "global.secrets.keyManagement.aws_kms.secretName is required when key management provider is aws and create is true" }}
{{- end }}
{{- if not .Values.global.secrets.keyManagement.aws_kms.values.accessKeyId }}
  {{- fail "global.secrets.keyManagement.aws_kms.values.accessKeyId is required when key management provider is aws and create is true" }}
{{- end }}
{{- if not .Values.global.secrets.keyManagement.aws_kms.values.secretAccessKey }}
  {{- fail "global.secrets.keyManagement.aws_kms.values.secretAccessKey is required when key management provider is aws and create is true" }}
{{- end }}

# Secret Resource
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.keyManagement.aws_kms.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.global.secrets.keyManagement.aws_kms.keys.accessKeyId }}: {{ .Values.global.secrets.keyManagement.aws_kms.values.accessKeyId | quote }}
  {{ .Values.global.secrets.keyManagement.aws_kms.keys.secretAccessKey }}: {{ .Values.global.secrets.keyManagement.aws_kms.values.secretAccessKey | quote }}
  {{- if .Values.global.secrets.keyManagement.aws_kms.values.sessionToken }}
  {{ .Values.global.secrets.keyManagement.aws_kms.keys.sessionToken }}: {{ .Values.global.secrets.keyManagement.aws_kms.values.sessionToken | quote }}
  {{- end }}
{{- end }}
