{{- if .Values.global.secrets.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.blobStoreSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-studio.labels" . | nindent 4 }}
type: Opaque
data:
  # Azure Blob Storage
  {{- if .Values.global.secrets.values.blobStorage.azureStorageAccountName }}
  azure-storage-account-name: {{ .Values.global.secrets.values.blobStorage.azureStorageAccountName | b64enc | quote }}
  {{- end }}

  {{- if .Values.global.secrets.values.blobStorage.azureStorageAccountKey }}
  azure-storage-account-key: {{ .Values.global.secrets.values.blobStorage.azureStorageAccountKey | b64enc | quote }}
  key: {{ .Values.global.secrets.values.blobStorage.azureStorageAccountKey | b64enc | quote }}
  {{- end }}

{{- end }}
