{{- if .Values.global.secrets.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.idpSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "governance-studio.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.global.secrets.values.idp.clientId | b64enc | quote }}
  client-secret: {{ .Values.global.secrets.values.idp.clientSecret | b64enc | quote }}
  {{- if eq (index .Values "auth-service").config.idp.provider "auth0" }}
  {{- if .Values.global.secrets.values.idp.auth0.managementClientId }}
  mgmt-client-id: {{ .Values.global.secrets.values.idp.auth0.managementClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.values.idp.auth0.managementClientSecret }}
  mgmt-client-secret: {{ .Values.global.secrets.values.idp.auth0.managementClientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
