# Auth0 Provider Configuration for SaaS Deployment
# This values file configures the auth-service to use Auth0 as the identity provider

config:
  # CORS is disabled by default as ingress controller handles it
  cors:
    enabled: false
    origins: "*"

  idp:
    provider: "auth0"
    issuer: "https://your-tenant.auth0.com/"
    clientId: "your-auth0-client-id"
    clientSecret: "your-auth0-client-secret"

    # Auth0-specific configuration
    auth0:
      domain: "your-tenant.auth0.com"
      managementClientId: "your-management-api-client-id"
      managementClientSecret: "your-management-api-client-secret"
      managementAudience: "https://your-tenant.auth0.com/api/v2/"
      apiIdentifier: "https://api.your-app.com"
      defaultConnection: "Username-Password-Authentication"
      defaultRoles: ["user"]
      sendInvitationEmail: true

    # Use existing secret for production
    # existingSecret: "auth-service-auth0-credentials"
    # existingSecretKeys:
    #   clientId: "client-id"
    #   clientSecret: "client-secret"
    #   managementClientId: "mgmt-client-id"
    #   managementClientSecret: "mgmt-client-secret"

  # Database configuration for SaaS
  database:
    # Use managed database service
    host: "your-rds-endpoint.amazonaws.com"
    port: 5432
    name: "auth_service"
    user: "auth_service_user"
    sslMode: "require"
    # Use existing secret for credentials
    existingSecret: "auth-service-db-credentials"
    existingSecretKeys:
      password: "password"

  # Key Vault configuration for SaaS
  keyVault:
    provider: "azure"
    azure:
      vaultUrl: "https://your-keyvault.vault.azure.net/"
      tenantId: "your-azure-tenant-id"
      # Use managed identity or existing secret
      existingSecret: "auth-service-keyvault-credentials"
      existingSecretKeys:
        clientId: "client-id"
        clientSecret: "client-secret"

# Production-ready settings for SaaS
replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

# Enable metrics for monitoring
metrics:
  enabled: true
  port: 9090
  path: "/metrics"

# Health checks
healthCheck:
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5

# Ingress configuration for SaaS
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: auth.your-saas-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: auth-service-tls
      hosts:
        - auth.your-saas-domain.com
